
    name: Publish Docker image

    on:
        push:
            branches: ['main']
    jobs:
        push_to_registry:
            name: Push Docker image to Docker Hub
            runs-on: ubuntu-latest
            steps:
                -   name: Checkout the repository
                    uses: actions/checkout@v4

                -   name: Login to Docker Hub
                    uses: docker/login-action@v4
                    with:
                        username: ${{secrets.DOCKER_USERNAME}}
                        password: ${{secrets.DOCKER_PASSWORD}}


                -   name: Build and Push Docker image
                    uses: docker/build-action@v4
                    with:
                        context: .
                        push: true
                        tags: ${{steps.meta.outputs.tags}}
                        labels: ${{steps.meta.outputs.labels}}
